config/routes.rb
Pmb::Application.routes.draw do
  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end
  resources :settings
  resources :forms

  namespace :admin do
    resources :settings do
      collection do
        get 'sms'
        get 'mail'
      end
    end
    resources :forms do
      collection do
        get 'reply_email_manual' 
        get 'remove'
        post 'remove_multiple'
      end
    end
  end

  root :to => 'forms#new'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :username, :password, :key, :ta, :no_hp, :email, :du, :jas_seragam, :ku, :kp, :glk_a, :glk_b, :glb1_a, :glb1_b, :glb2_a, :glb2_b
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_setting, only: [:show, :edit, :update, :destroy]
  respond_to :html
  include ApplicationHelper

  def index
    @setting = Setting.first
    respond_with(@settings)
  end

  def show
    respond_with(@setting)
  end

  def new
    @setting = Setting.new
    respond_with(@setting)
  end

  def edit
  end

  def create
    @setting = Setting.new(params[:setting])
    if @setting.save
      redirect_to admin_settings_path, :notice => "Successfully created setting."  
    else  
      render :action => 'new'  
    end  
  end

  def update
    @setting.update_attributes(params[:setting])
    redirect_to admin_settings_path, :notice => "Successfully updated setting."
  end

  def destroy
    @setting.destroy
    respond_with(@setting)
  end
  
  def sms
    testing("#{Setting.first.no_hp}", "Test SMS Konfigurasi")
    redirect_to admin_settings_path
  end
  
  def mail
    Welcome.send_reply("#{Setting.first.email}").deliver
    redirect_to admin_settings_path
  end

  private
  def set_setting
    @setting = Setting.find(params[:id])
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!
  #load_and_authorize_resource
  before_filter :set_setting, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @settings = Setting.all
    respond_with(@settings)
  end

  def show
    respond_with(@setting)
  end

  def new
    @setting = Setting.new
    respond_with(@setting)
  end

  def edit
  end

  def create
    @setting = Setting.new(params[:setting])
    #respond_with(@setting)
    if @setting.save
      redirect_to @setting, :notice => "Successfully created setting."  
    else  
      render :action => 'new'  
    end  
  end

  def update
    @setting.update_attributes(params[:setting])
    redirect_to settings_path, :notice => "Successfully updated setting."
  end

  def destroy
    @setting.destroy
    respond_with(@setting)
  end

  private
  def set_setting
    @setting = Setting.find(params[:id])
  end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/settings/_form.html.erb
<%= form_for ([:admin, @setting]), :html => {:class => "form-horizontal"} do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>
        <ul>
            <% @setting.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <br />
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">Tahun Ajaran</label>
      <div class="col-sm-5">
          <%= f.text_field :ta, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">HP Penerima Pendaftaran</label>
      <div class="col-sm-5">
          <%= f.text_field :no_hp, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">Email Penerima Pendaftaran</label>
      <div class="col-sm-5">
          <%= f.text_field :email, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">Daftar Ulang</label>
      <div class="col-sm-5">
          <%= f.text_field :du, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">Pengambilan Jas dan Pengukuran Seragam</label>
      <div class="col-sm-5">
          <%= f.text_field :jas_seragam, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">Kuliah Umum</label>
      <div class="col-sm-5">
          <%= f.text_field :ku, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-5 control-label">Kuliah Perdana</label>
      <div class="col-sm-5">
          <%= f.text_field :kp, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-3 control-label">Gelombang Khusus</label>
      <div class="col-sm-2">
          <%= f.text_field :glk_a, :class => "form-control"  %>
      </div>
      <label for="inputEmail3" class="col-sm-1 control-label">s/d</label>
      <div class="col-sm-2">
          <%= f.text_field :glk_b, :class => "form-control" %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-3 control-label">Gelombang I</label>
      <div class="col-sm-2">
          <%= f.text_field :glb1_a, :class => "form-control"  %>
      </div>
      <label for="inputEmail3" class="col-sm-1 control-label">s/d</label>
      <div class="col-sm-2">
          <%= f.text_field :glb1_b, :class => "form-control" %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-3 control-label">Gelombang II</label>
      <div class="col-sm-2">
          <%= f.text_field :glb2_a, :class => "form-control"  %>
      </div>
      <label for="inputEmail3" class="col-sm-1 control-label">s/d</label>
      <div class="col-sm-2">
          <%= f.text_field :glb2_b, :class => "form-control" %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-3 control-label">Username SMS</label>
      <div class="col-sm-4">
          <%= f.text_field :username, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-3 control-label">Password SMS</label>
      <div class="col-sm-4">
          <%= f.text_field :password, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-3 control-label">Key SMS</label>
      <div class="col-sm-5">
          <%= f.text_field :key, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
          <%= f.submit 'Update Setting', :class => 'btn btn-default' %>&nbsp;<%= link_to 'Test SMS', sms_admin_settings_path, :class => 'btn btn-primary'  %>&nbsp;<%= link_to 'Test Email', mail_admin_settings_path, :class => 'btn btn-primary'  %>
      </div>
  </div>
<% end %>

app/views/admin/settings/edit.html.erb
<div class="page-header">
    <h4>SETTING</h4>
</div>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/admin/settings/index.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>SETTING</h5>
            </div>
            <%= render 'form' %>
        </div>
    </div>
    <% unless Setting.first.username.blank? && Setting.first.password.blank? && Setting.first.key.blank? %>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>INFORMASI NOTIFIKASI SMS</h5>
            </div>
        </div>
    </div>
    <% end %>
</div>