config/routes.rb
Pmb::Application.routes.draw do
  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end
  resources :settings
  resources :forms

  namespace :admin do
    resources :settings do
      collection do
        get 'sms'
        get 'mail'
      end
    end
    resources :forms do
      collection do
        get 'reply_email_manual' 
        get 'remove'
        post 'remove_multiple'
      end
    end
  end

  root :to => 'forms#new'

end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_form, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @forms = Form.by_year(Setting.first.ta).order("id DESC").where("remove = ?", false)
    respond_to do |format|
      format.html {}
      format.csv { send_data @forms.to_csv }
      format.xls # { send_data @forms.to_csv(col_sep: "\t") }
    end
  end

  def show
    year = @form.created_at.strftime("%Y").to_i
    month = @form.created_at.strftime("%m").to_i
    date = @form.created_at.strftime("%d").to_i
    @form.update_attribute(:gelombang, gelombang(Date.new(year, month, date)))
    @form.update_attribute(:balasan, @form.created_at + 7.day)
    respond_with(@form)
  end

  def new
    @form = Form.new
    @reg = Form.all.size + 1
    respond_with(@form)
  end

  def edit
  end

  def create
    reg = Form.all.size + 1
    @form = Form.new(params[:form])
    @form.reg = "#{"%04d" % reg}/#{Setting.first.ta}"
    @form.ta = "#{Setting.first.ta}"
    @form.save
    redirect_to root_url, :notice => "Successfully Entry ....."
  end

  def update
    @form.update_attributes(params[:form])
    respond_with(@form)
  end

  def destroy
    @form.destroy
    redirect_to admin_forms_path
  end
  
  def reply_email_manual
    @form = Form.find(params[:id])
    Welcome.surat_balasan(@form).deliver
    redirect_to admin_forms_path
  end

  def remove
    @form = Form.find(params[:id])
    @form.update_attribute(:remove, true)
    redirect_to admin_forms_path
  end
  
  def remove_multiple
    Form.where(:id => params[:forms]).update_all(:remove => true)
    redirect_to admin_forms_path
  end
end
  

private
def set_form
  @form = Form.find(params[:id])
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  #before_filter :authenticate_user!
  before_filter :set_form, only: [:show, :edit, :update, :destroy]
  require 'active_support/core_ext'

  respond_to :html

  def index
    @forms = Form.all
    respond_with(@forms)
  end

  def show
    respond_with(@form)
  end

  def new
    @year = Time.now.strftime("%Y").to_i
    @month = Time.now.strftime("%m").to_i
    @date = Time.now.strftime("%d").to_i
    @form = Form.new
    @reg = Form.all.size + 333
    respond_with(@form)
  end

  def edit
  end

  def create
    registrar = Form.all.size + 333
    year = Time.now.strftime("%Y").to_i
    month = Time.now.strftime("%m").to_i
    date = Time.now.strftime("%d").to_i
    @form = Form.new(params[:form])
    @form.reg = "#{"%04d" % registrar}/#{Setting.first.ta}"
    @form.ta = "#{Setting.first.ta}"
    @form.gelombang = gelombang(Date.new(year, month, date))
    respond_to do |format|
      if @form.save
        @form.update_attribute(:balasan, @form.created_at + 7.day)
        Welcome.send_data(@form, Setting.first.email).deliver
        sms_notivikasi("#{Setting.first.no_hp}", "PMB AMA YPK : Ada Pengdaftar Online #{@form.reg}")
        format.html { redirect_to(@form, :notice => 'Selamat !! data anda telah masuk dalam database kami') }
        format.xml  { render :xml => @form, :status => :created, :location => @form }
      else
        format.html { redirect_to root_url }
        format.xml  { render :xml => @form.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @form.update_attributes(params[:form])
    respond_with(@form)
  end

  def destroy
    @form.destroy
    respond_with(@form)
  end
  
  def sms
    testing("085731775266", "Testing SMS Konfigurasi")
  end

  private
    def set_form
      @form = Form.find(params[:id])
    end
end

app/helpers/admin/forms_helper.rb
module Admin::FormsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/admin/forms/_form.html.erb
<%= form_for(@form, :validate => true, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

        <ul>
            <% @form.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <div class="panel-heading">
    <h5>DATA PRIBADI</h5>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">No Pendaftaran</label>
      <div class="col-sm-2">
          <%= f.text_field :reg, :disabled=>true, :class => "form-control", :value => "#{"%04d" % @reg}"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Nama Lengkap</label>
      <div class="col-sm-4">
          <%= f.text_field :name, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Alamat Lengkap</label>
      <div class="col-sm-4">
          <%= f.text_area :alamat, :rows => "3", :class => "form-control"  %>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Tempat Tanggal Lahir</label>
      <div class="col-sm-4">
          <%= f.text_field :ttl, :class => "form-control"  %>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Telp / Handphone</label>
      <div class="col-sm-4">
          <%= f.text_field :tlp_hp, :class => "form-control"  %>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
      <div class="col-sm-4">
          <%= f.text_field :email, :class => "form-control"  %>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Jenis Kelamin</label>
      <div class="col-sm-4">
          <div class="radio">
              <label>
                  <input type="radio" name="form[jk]" id="jk1" value="Laki - Laki" checked>
                  Laki laki
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[jk]" id="jk2" value="Perempuan">
                  Perempuan
              </label>
          </div>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Tinggi Badan</label>
      <div class="col-sm-1">
          <%= f.text_field :tb, :class => "form-control"  %>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Berat Badan</label>
      <div class="col-sm-1">
          <%= f.text_field :bb, :class => "form-control"  %>
      </div>
  </div>

  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Agama</label>
      <div class="col-sm-4">
          <div class="radio">
              <label>
                  <input type="radio" name="form[agama]" id="agama1" value="Islam" checked>
                  Islam
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[agama]" id="agama2" value="Katolik">
                  Katolik
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[agama]" id="agama3" value="Kristen">
                  Kristen
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[agama]" id="agama4" value="Hindu">
                  Hindu
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[agama]" id="agama5" value="Budha">
                  Budha
              </label>
          </div>
      </div>
  </div>
  <div class="panel-heading">
  <h5>DATA SEKOLAH</h5>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Asal Sekolah</label>
      <div class="col-sm-4">
          <%= f.text_field :asal_sekolah, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Jurusan</label>
      <div class="col-sm-4">
          <%= f.text_field :jurusan, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Alamat</label>
      <div class="col-sm-4">
          <%= f.text_area :alamat_sekolah, :rows => "3", :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
      <div class="col-sm-4">
          <%= f.text_field :email_sekolah, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Website</label>
      <div class="col-sm-4">
          <%= f.text_field :web_sekolah, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Nama Guru BK</label>
      <div class="col-sm-4">
          <%= f.text_field :nama_gbk, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Telp / Handphone</label>
      <div class="col-sm-4">
          <%= f.text_field :tlp_bk, :class => "form-control"  %>
      </div>
  </div>
  <div class="panel-heading">
    <h5>DATA ORANG TUA / WALI</h5>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Nama Orang Tua / Wali</label>
      <div class="col-sm-4">
          <%= f.text_field :nama_ortu, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Telp / Handphone</label>
      <div class="col-sm-4">
          <%= f.text_field :telp_ortu, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Alamat Lengkap</label>
      <div class="col-sm-4">
          <%= f.text_area :alamat_ortu, :rows => "3", :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Pekerjaan Orang Tua/Wali</label>
      <div class="col-sm-4">
          <%= f.text_field :job_ortu, :class => "form-control"  %>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Penghasilan Orang Tua/Wali</label>
      <div class="col-sm-8">
          <div class="radio">
              <label>
                  <input type="radio" name="form[penghasilan_ortu]" id="penghasilan_ortu1" value="< Rp. 1.500.000" checked>
                  < Rp. 1.500.000
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[penghasilan_ortu]" id="penghasilan_ortu2" value="Rp. 1.500.000 s/d Rp. 2.500.000">
                  Rp. 1.500.000 s/d Rp. 2.500.000
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[penghasilan_ortu]" id="penghasilan_ortu3" value="Rp. 2.500.000 s/d Rp. 3.500.000">
                  Rp. 2.500.000 s/d Rp. 3.500.000
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[penghasilan_ortu]" id="penghasilan_ortu4" value="> Rp. 3.500.000">
                   > Rp. 3.500.000
              </label>
          </div>
      </div>
  </div>
  <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Pilihan Jurusan</label>
      <div class="col-sm-10">
          <div class="radio">
              <label>
                  <input type="radio" name="form[prodi]" id="prodi1" value="Manajemen Administrasi Rumah Sakit">
                  Manajemen Administrasi Rumah Sakit
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[prodi]" id="prodi2" value="Manajemen Administrasi Obat dan Farmasi">
                  Manajemen Administrasi Obat dan Farmasi
              </label>
          </div>
          <div class="radio">
              <label>
                  <input type="radio" name="form[prodi]" id="prodi3" value=" Manajemen Administrasi Perkantoran">
                   Manajemen Administrasi Perkantoran
              </label>
          </div>
      </div>
  </div>
  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Kirimkan', :class => 'btn btn-default' %>
      </div>
  </div>
<% end %>

app/views/admin/forms/edit.html.erb
<h1>Editing form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/admin/forms/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h5>DATA CALON MAHASISWA</h5><span style="float: right; margin-top: -27px;"><%= link_to '<i class="glyphicon glyphicon-cloud-download"></i>'.html_safe, admin_forms_path(format: "xls") %> Download Exel<% if current_user.admin == true %>&nbsp;&nbsp;<input type="checkbox" id="selectAll" value="selectAll"> Pilih Semua<% end %></span>
    </div>  
    <%= form_tag remove_multiple_admin_forms_path do %>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="datatables">
        <thead>
            <tr>
                <th>NOMOR</th>
                <th>NAMA</th>
                <th>ALAMAT</th>
                <th>NO TELP / HP</th>
                <th>TGL MASUK</th>
                <th>TGL BALAS</th>
                 <th width="4%"><% if current_user.admin == true %><%= submit_tag "Hapus", :class => 'btn btn-primary' %><% end %></th>
            </tr>
        </thead>
        <tbody>
            <% @forms.each do |form| %>
              <tr>
                  <td class="col-md-1"><%= form.reg %></td>
                  <td class="col-md-1"><%= form.name %></td>
                  <td class="col-md-3"><%= form.alamat_pribadi_dusun %>&nbsp;<%= form.alamat_pribadi_rt %><br/><%= form.alamat_pribadi_kecamatan %>&nbsp;<%= form.alamat_pribadi_kelurahan_desa %><br /><%= form.alamat_pribadi_kabupaten %><%= form.alamat_pribadi_propinsi %></td>
                  <td class="col-md-1"><%= form.tlp_hp %></td>
                  <td class="col-md-1"><%= form.created_at.strftime("%d-%m-%Y") %></td>
                  <td class="col-md-1"><%= form.balasan.to_date.strftime("%d-%m-%Y") %></td>
                  <td class="col-md-2"><%#= link_to '<i class=" glyphicon glyphicon-envelope"></i>'.html_safe, reply_email_manual_admin_forms_path(:id => form.id), 'data-placement' => "top",  'title' => "Kirim Balasan Email Manual " %><%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, admin_form_path(form), 'data-placement' => "top",  'title' => "Tampilkan Lebih Lengkap"  %>
<% if current_user.admin == true %>
                        &nbsp;
                        <%= check_box_tag "forms[]", form.id %>
                      <% end %>
</td>
            <% end %>
        </tbody>
    </table>
    <% end %>
</div>

app/views/admin/forms/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">No Registrasi</Data></Cell>
        <Cell><Data ss:Type="String">Tanggal Daftar</Data></Cell>
        <Cell><Data ss:Type="String">Nama Lengkap</Data></Cell>
        <Cell><Data ss:Type="String">Alamat 1</Data></Cell>
        <Cell><Data ss:Type="String">Alamat 2</Data></Cell>
        <Cell><Data ss:Type="String">Alamat 3</Data></Cell>
        <Cell><Data ss:Type="String">Tempat Tanggal Lahir</Data></Cell>
        <Cell><Data ss:Type="String">Telp / HP</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Jenis Kelamin</Data></Cell>
        <Cell><Data ss:Type="String">Tinggi Badan</Data></Cell>
        <Cell><Data ss:Type="String">Berat Badan</Data></Cell>
        <Cell><Data ss:Type="String">Agama</Data></Cell>
        <Cell><Data ss:Type="String">Asal Sekolah</Data></Cell>
        <Cell><Data ss:Type="String">Alamat Sekolah 1</Data></Cell>
        <Cell><Data ss:Type="String">Alamat Sekolah 2</Data></Cell>
        <Cell><Data ss:Type="String">Alamat Sekolah 3</Data></Cell>
        <Cell><Data ss:Type="String">Jurusan</Data></Cell>
        <Cell><Data ss:Type="String">Email Sekolah</Data></Cell>
        <Cell><Data ss:Type="String">Web Sekolah</Data></Cell>
        <Cell><Data ss:Type="String">Nama Guru BK</Data></Cell>
        <Cell><Data ss:Type="String">Telp Guru BK</Data></Cell>
        <Cell><Data ss:Type="String">Nama Orang Tua</Data></Cell>
        <Cell><Data ss:Type="String">Telp Orang Tua</Data></Cell>
        <Cell><Data ss:Type="String">Alamat Orang Tua 1</Data></Cell>
        <Cell><Data ss:Type="String">Alamat Orang Tua 2</Data></Cell>
        <Cell><Data ss:Type="String">Alamat Orang Tua 3</Data></Cell>
        <Cell><Data ss:Type="String">Pekerjaan Orang Tua</Data></Cell>
        <Cell><Data ss:Type="String">Penghasilan Orang Tua</Data></Cell>
        <Cell><Data ss:Type="String">Program Studi</Data></Cell>
      </Row>
    <% @forms.each do |form| %>
      <Row>
        <Cell><Data ss:Type="String"><%= form.reg %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.created_at.strftime("%d %m %Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_pribadi_dusun %> <%= form.alamat_pribadi_rt %><%= form.alamat_pribadi_kelurahan_desa %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_pribadi_kecamatan %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_pribadi_kabupaten %> <%= form.alamat_pribadi_propinsi %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.ttl %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.tlp_hp %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.jk %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.tb %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.bb %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.agama %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.asal_sekolah %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_sekolah_dusun %> <%= form.alamat_sekolah_rt %> <%= form.alamat_sekolah_kelurahan_desa %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_sekolah_kecamatan %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_sekolah_kabupaten %> <%= form.alamat_sekolah_propinsi %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.jurusan %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.email_sekolah %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.web_sekolah %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.nama_gbk %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.tlp_bk %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.nama_ortu %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.telp_ortu %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_ortu_dusun %> <%= form.alamat_ortu_rt %> <%= form.alamat_ortu_kelurahan_desa %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_ortu_kecamatan %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.alamat_ortu_kabupaten %> <%= form.alamat_ortu_propinsi %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.job_ortu %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.penghasilan_ortu %></Data></Cell>
        <Cell><Data ss:Type="String"><%= form.prodi %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/forms/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
    <div class="panel-heading">
        <h5>DATA LENGKAP CALON MAHASISWA</h5><h5><span style="float: right; margin-top: -27px;"><%= @form.gelombang %></span></h5>
    </div>
    <div class="content">
        <div class="panel panel-default">
        <div class="panel-heading">
            <h6>DATA PRIBADI</h6>
        </div>
        </div>
        <div style="padding: 0px 15px;">
        <p>
            <b>Pendaftaran:</b>
            <%= @form.reg %>
        </p>
        <p>
            <b>Nama:</b>
            <%= @form.name %>
        </p>

        <p>
            <b>Alamat:</b>
            <%= @form.alamat_pribadi_dusun %>&nbsp;<%= @form.alamat_pribadi_rt %>&nbsp;<%= @form.alamat_pribadi_kecamatan %>&nbsp;<%= @form.alamat_pribadi_kelurahan_desa %>&nbsp;<%= @form.alamat_pribadi_kabupaten %>&nbsp;<%= @form.alamat_pribadi_propinsi %>
        </p>

        <p>
            <b>Tempat Tanggal Lahir:</b>
            <%= @form.ttl %>
        </p>

        <p>
            <b>Telp / HP:</b>
            <%= @form.tlp_hp %>
        </p>

        <p>
            <b>Email:</b>
            <%= @form.email %>
        </p>

        <p>
            <b>Jenis Kelamin:</b>
            <%= @form.jk %>
        </p>

        <p>
            <b>Tinggi Badan:</b>
            <%= @form.tb %>
        </p>

        <p>
            <b>Berat Badan:</b>
            <%= @form.bb %>
        </p>

        <p>
            <b>Agama:</b>
            <%= @form.agama %>
        </p>
        </div>
        <div class="panel panel-default">
        <div class="panel-heading">
            <h6>DATA SEKOLAH</h6>
        </div>
        </div>
        <div style="padding: 0px 15px;">
        <p>
            <b>Asal Sekolah:</b>
            <%= @form.asal_sekolah %>
        </p>

        <p>
            <b>Alamat sekolah:</b>
            <%= @form.alamat_sekolah_dusun %>&nbsp;<%= @form.alamat_sekolah_rt %>&nbsp;<%= @form.alamat_sekolah_kecamatan %>&nbsp;<%= @form.alamat_sekolah_kelurahan_desa %>&nbsp;<%= @form.alamat_sekolah_kabupaten %>&nbsp;<%= @form.alamat_sekolah_propinsi %>
        </p>

        <p>
            <b>Jurusan:</b>
            <%= @form.jurusan %>
        </p>

        <p>
            <b>Email Sekolah:</b>
            <%= @form.email_sekolah %>
        </p>

        <p>
            <b>Web Sekolah:</b>
            <%= @form.web_sekolah %>
        </p>

        <p>
            <b>Nama Guru BK:</b>
            <%= @form.nama_gbk %>
        </p>

        <p>
            <b>Telp Guru BK:</b>
            <%= @form.tlp_bk %>
        </p>
        </div>
        <div class="panel panel-default">
        <div class="panel-heading">
            <h6>DATA KELUARGA</h6>
        </div>
        </div>
        <div style="padding: 0px 15px;">
        <p>
            <b>Nama Orang Tua:</b>
            <%= @form.nama_ortu %>
        </p>

        <p>
            <b>Telp Orang Tua:</b>
            <%= @form.telp_ortu %>
        </p>

        <p>
            <b>Alamat Orang Tua:</b>
            <%= @form.alamat_ortu_dusun %>&nbsp;<%= @form.alamat_ortu_rt %>&nbsp;<%= @form.alamat_ortu_kecamatan %>&nbsp;<%= @form.alamat_ortu_kelurahan_desa %>&nbsp;<%= @form.alamat_ortu_kabupaten %>&nbsp;<%= @form.alamat_ortu_propinsi %>
        </p>

        <p>
            <b>Pekerjaan Orang Tua:</b>
            <%= @form.job_ortu %>
        </p>

        <p>
            <b>Penghasilan Orang Tua:</b>
            <%= @form.penghasilan_ortu %>
        </p>

        <p>
            <b>Program Studi:</b>
            <%= @form.prodi %>
        </p>
        </div>
    </div>
</div>


<%= link_to 'Kembali', admin_forms_path, :class => 'btn btn-primary' %>
<br />